/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ChangeRequest = IDL.Record({
  'submittedTime' : Time,
  'content' : IDL.Text,
  'submittedBy' : IDL.Principal,
  'reviewed' : IDL.Bool,
  'accepted' : IDL.Bool,
});
export const ChangeRequestInput = IDL.Record({ 'content' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAll' : IDL.Func([], [IDL.Vec(ChangeRequest)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markReviewed' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'submitChangeRequest' : IDL.Func([ChangeRequestInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChangeRequest = IDL.Record({
    'submittedTime' : Time,
    'content' : IDL.Text,
    'submittedBy' : IDL.Principal,
    'reviewed' : IDL.Bool,
    'accepted' : IDL.Bool,
  });
  const ChangeRequestInput = IDL.Record({ 'content' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAll' : IDL.Func([], [IDL.Vec(ChangeRequest)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markReviewed' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'submitChangeRequest' : IDL.Func([ChangeRequestInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };